#!/bin/bash

GRUB_CONFIG=$(sudo find /boot -name "grub.cfg")
PRODUCER=$(sudo dmidecode -s system-product-name)

sudo pacman -Syyu
sudo pacman -S curl

echo "Installation et configuration de Plasma..."

    sudo pacman -S xorg sddm plasma kde-applications
	sudo sed -i 's/Current=/Current=breeze/' /usr/lib/sddm/sddm.conf.d/default.conf
	sudo systemctl enable sddm

echo "Installation et configuration de Oh My Zsh..."

    sudo pacman -S zsh
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
	chsh -s $(which zsh)

	PLUGINS=$(ls zsh-plugins)

	for plugin in $PLUGINS; do
		cp -r zsh-plugins/$plugin ~/.oh-my-zsh/plugins
	done

	sed -i -r 's/plugins=(.*)/plugins=($PLUGINS git)/g' ~/.zshrc

echo "Installation des logiciels tiers..."

        USER_INPUT=""
        SOFTWARES=$(ls "applications-install")

	mkdir temp 2>/dev/null

        while [[ 0==0 ]]; do

                i=1;

                for script in $SOFTWARES; do
                        echo "[$i] $script"
                        i=$(($i+1));
                done

                read -p "[1-$i/a(ll)/c(ontinue)]: " USER_INPUT

                if [[ $USER_INPUT == "c" ]]; then
                        break
		fi

                if [[ $USER_INPUT == "a" ]]; then
                        for script in $SOFTWARES; do
                                sudo ./applications-install/$script;
                        done
                        continue
		fi
		
		sudo ./applications-install/$(echo $SOFTWARES | cut -d" " -f$USER_INPUT)

        done

echo "Configuration de GRUB..."
	if [[ $GRUB_CONFIG != "" ]]; then

		sudo cp -r grub_themes/custom /usr/share/grub/themes
		cat grub_themes/default_grub | sudo tee -a /etc/default/grub

		if [[ $PRODUCER == "Mac"* ]]; then

                	sudo pacman -S refind efibootmgr
			sudo refind-install

			sudo cp /usr/share/grub/themes/custom/theme.txt.mac /usr/share/grub/themes/custom/theme.txt
			sudo sed -i 's/timeout 10/timeout -1/g' /boot/efi/EFI/refind/refind.conf
			sudo sed -i 's/#default_selection 1/default_selection 3/g' /boot/efi/EFI/refind/refind.conf
			sudo cp grub_themes/40_custom /etc/grub.d/40_custom

			read -p "Quel est le disk EFI ? " efi_disk
			sudo sed -i "s/DISK_EFI_TO_CHANGE/$efi_disk/g" /etc/grub.d/40_custom

			echo "Pensez à changer l'ordre de boot avec efibootmgr."

		else
			sudo cp /usr/share/grub/themes/custom/theme.txt.classic /usr/share/grub/themes/custom/theme.txt
		fi

		for config in $GRUB_CONFIG; do
			sudo grub-mkconfig -o $config;
		done

	else
		echo "Grub is not installed."
	fi


rm -rf /tmp/installation-script
