#!/bin/bash

GRUB_CONFIG=$(sudo find /boot -name "grub.cfg")
PRODUCER=$(sudo dmidecode -s system-product-name)

sudo apt update && sudo apt upgrade -y
sudo apt install curl wget -y

echo "Installation et configuration de Plasma..."

	sudo apt install xorg sddm kde-plasma-desktop konsole -y
	sudo sed -i 's/Current=/Current=breeze/' /usr/lib/sddm/sddm.conf.d/default.conf
	sudo systemctl enable sddm

echo "Installation et configuration de Oh My Zsh..."

    sudo apt install zsh -y
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

	PLUGINS=$(ls zsh-plugins)

	for plugin in $PLUGINS; do
		cp -r zsh-plugins/$plugin ~/.oh-my-zsh/plugins
	done

	sed -i -r 's/plugins=(.*)/plugins=($PLUGINS git)/g' ~/.zshrc

echo "Installation des logiciels tiers..."

        USER_INPUT=""
        SOFTWARES=$(ls "applications-install")

	mkdir temp 2>/dev/null

        while [[ 0==0 ]]; do

                i=1;

                for script in $SOFTWARES; do
                        echo "[$i] $script"
                        i=$(($i+1));
                done

                read -p "[1-$i/a(ll)/c(ontinue)]: " USER_INPUT

                if [[ $USER_INPUT == "c" ]]; then
                        break
		fi

                if [[ $USER_INPUT == "a" ]]; then
                        for script in $SOFTWARES; do
								echo "Installation de $script..."
                                ./applications-install/$script;
                        done
                        break
		fi
		
		echo "Installation de $(echo $SOFTWARES | cut -d" " -f$USER_INPUT)..."
		./applications-install/$(echo $SOFTWARES | cut -d" " -f$USER_INPUT)

        done

echo "Configuration de GRUB..."
	if [[ $GRUB_CONFIG != "" ]]; then

		sudo cp -r grub_themes/custom /usr/share/grub/themes/custom
		cat grub_themes/default_grub | sudo tee -a /etc/default/grub

		if [[ $PRODUCER == "Mac"* ]]; then

            sudo apt install refind efibootmgr -y
			sudo refind-install

			sudo cp /usr/share/grub/themes/custom/theme.txt.mac /usr/share/grub/themes/custom/theme.txt
			sudo sed -i 's/timeout 10/timeout -1/g' /boot/efi/EFI/refind/refind.conf
			sudo sed -i 's/#default_selection 1/default_selection 3/g' /boot/efi/EFI/refind/refind.conf
			sudo cp grub_themes/40_custom /etc/grub.d/40_custom

			read -p "Quel est le disk EFI ? " efi_disk
			sudo sed -i "s/DISK_EFI_TO_CHANGE/$efi_disk/g" /etc/grub.d/40_custom

			echo "Pensez à changer l'ordre de boot avec efibootmgr."

		else
			sudo cp /usr/share/grub/themes/custom/theme.txt.classic /usr/share/grub/themes/custom/theme.txt
		fi

		for config in $GRUB_CONFIG; do
			sudo grub-mkconfig -o $config;
		done

	else
		echo "Grub is not installed."
	fi


sudo rm -rf temp
