#!/bin/bash

cd /tmp/install-script

if [[ $(uname -m) == "x86_64" ]]; then

	curl -sSO https://downloads.1password.com/linux/tar/stable/x86_64/1password-latest.tar.gz

elif [[ $(uname -m) == "aarch64" ]]; then

	curl -sSO https://downloads.1password.com/linux/tar/stable/aarch64/1password-latest.tar.gz

else

	echo "Impossible d'installer 1password."
	cd
	exit

fi


sudo tar -xf 1password-latest.tar.gz
sudo mkdir -p /opt/1Password
sudo mv 1password-*/* /opt/1Password
sudo /opt/1Password/after-install.sh
cd

echo "1password installé avec succès !"
