#!/bin/bash

if [[ -n $(ls /etc | grep apt) ]]; then

	sudo apt install adb

elif [[ -n $(ls /etc | grep dnf) ]]; then

	sudo dnf install adb

elif [[ -n $(ls /etc | grep pacman) ]]; then

	sudo pacman -S android-tools

fi

echo "ADB installé avec succès !"
