#!/bin/bash

cd temp

if [[ -n $(ls /etc | grep apt) ]]; then

	sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
	echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
	sudo apt update
	sudo apt install brave-browser -y

elif [[ -n $(ls /etc | grep dnf) ]]; then

    sudo dnf install dnf-plugins-core -y
	sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
	sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
	sudo dnf install brave-browser -y
	
elif [[ -n $(ls /etc | grep flatpak) ]]; then

	flatpak install brave -y

else

    echo "Impossible d'installer Brave."
    cd
    exit

fi

cd
echo "Brave installé avec succès !"
