#!/bin/bash

cd /tmp/install-script

if [[ $(which apt) != "apt not found" ]]; then

        sudo add-apt-repository multiverse
	sudo apt update && sudo apt upgrade -y
	sudo apt install steam

elif [[ $(which dnf) != "dnf not found" ]]; then

        sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
	sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
	sudo dnf install steam
	sudo rm ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6
	sudo rm ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libgcc_s.so.1

elif [[ $(which pacman) != "pacman not found" ]]; then

	sudo sed -i '/#\[multilib\]/,/#Include = \/etc\/pacman.d\/mirrorlist/s/^#//' /etc/pacman.conf
	sudo pacman -Syu
	sudo pacman -S steam

else

        echo "Impossible d'installer Steam."
        cd
        exit

fi

echo "Steam installé avec succès !"
