#!/bin/bash

cd temp

if [[ -n $(ls /etc | grep apt) ]]; then

    wget -O steam.deb https://cdn.cloudflare.steamstatic.com/client/installer/steam.deb
	sudo apt install ./steam.deb -y

elif [[ -n $(ls /etc | grep dnf) ]]; then

    sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y
	sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
	sudo dnf install steam -y
	sudo rm ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6
	sudo rm ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libgcc_s.so.1

elif [[ -n $(ls /etc | grep pacman) ]]; then

	sudo sed -i '/#\[multilib\]/,/#Include = \/etc\/pacman.d\/mirrorlist/s/^#//' /etc/pacman.conf
	sudo pacman -Syyu
	sudo pacman -S --noconfirm steam

else

        echo "Impossible d'installer Steam."
        cd
        exit

fi

cd
echo "Steam installé avec succès !"