#!/bin/bash

cd temp

if [[ -n $(ls /etc | grep apt) ]]; then

	sudo apt install wireshark

elif [[ -n $(ls /etc | grep dnf) ]]; then

	sudo dnf install wireshark wireshark-qt

elif [[ -n $(ls /etc | grep pacman) ]]; then

	sudo pacman -S wireshark-qt

else

	echo "Impossible d'installer Wireshark."
	cd
	exit

fi

echo "Wireshark installé avec succès !"
