#!/bin/bash

cd temp

if [[ -n $(ls /etc | grep apt) ]]; then

	sudo apt install wireshark -y

elif [[ -n $(ls /etc | grep dnf) ]]; then

	sudo dnf install wireshark wireshark-qt -y

elif [[ -n $(ls /etc | grep pacman) ]]; then

	sudo pacman -S --noconfirm wireshark-qt

else

	echo "Impossible d'installer Wireshark."
	cd
	exit

fi

cd
echo "Wireshark installé avec succès !"